language: node_js
env:
  - CXX="g++-4.8"
node_js:
  - "4"
  - "5"
addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8
    - gcc-4.8
services:
  - redis-server
sudo: false
